spring:
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  application:
    name: discodeit
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

#파일 저장 방식 변경 설정
discodeit:
  storage:
    type: ${STORAGE_TYPE:local}
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:.discodeit/data}
    s3:
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}
logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
info:
  app:
    name: Discodeit
    version: 1.7.0
  java:
    version: 17
  spring-boot:
    version: 3.4.0